### ISSUE TITLE
loop() vs main_program()

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/roboruka-demo01#1]
Do we want to use `main_program()` or Arduino's `loop()` in our example programs?

In `roboruka-demo01` we don't use the `loop()`
https://github.com/RoboticsBrno/roboruka-demo01/blob/f90f5fe1e656abfac775ab64deffcd04fc563f88/src/main.cpp#L21

and instead of we define `main_program()` function
https://github.com/RoboticsBrno/roboruka-demo01/blob/f90f5fe1e656abfac775ab64deffcd04fc563f88/src/main.cpp#L59

@haberturdeur (Tom Rohlínek) told me, that it could be harder for beginners (with knowledge of the Arduino platform) to work with the `main_program()` instead `loop()`.

What do you think @Tasssadar @yaqwsx @cednik?

Could you talk about that in term of the RBControl-light/beginner-library?

**Comment by Tasssadar** [comment]
474b3f92a3a836a6118a396a69bdf4b498542366 converted this to use the simplified library, which uses standard `setup()` and `loop()`, so closing.
